const STATE = {
  cars: [
    {
      id: 1,
      car: 'Audi',
      car_model: 'Cabriolet',
      color: 'Mauv',
      car_vin: '1GYS3KEF9CR093104',
      location: 'Russia',
    },
    {
      id: 2,
      car: 'Chevrolet',
      car_model: 'Corvette',
      color: 'Khaki',
      car_vin: '4JGCB2FE6BA577789',
      location: 'France',
    },
    {
      id: 3,
      car: 'Mercedes-Benz',
      car_model: '400E',
      color: 'Orange',
      car_vin: '1B3CB3HA5AD264932',
      location: 'France',
    },
    {
      id: 4,
      car: 'Dodge',
      car_model: 'Ram Van 1500',
      color: 'Red',
      car_vin: '5J6TF1H32BL089307',
      location: 'Russia',
    },
    {
      id: 5,
      car: 'Mercedes-Benz',
      car_model: 'SL-Class',
      color: 'Khaki',
      car_vin: 'SCBFC7ZA1EC887719',
      location: 'Poland',
    },
    {
      id: 6,
      car: 'Saab',
      car_model: '900',
      color: 'Yellow',
      car_vin: '1N6BF0KM3FN683179',
      location: 'Italy',
    },
    {
      id: 7,
      car: 'Volkswagen',
      car_model: 'rio',
      color: 'Violet',
      car_vin: '3GYFNCE34ES061426',
      location: 'Poland',
    },
    {
      id: 8,
      car: 'Mercury',
      car_model: 'Marauder',
      color: 'Puce',
      car_vin: 'WBALW7C58CC445422',
      location: 'Russia',
    },
    {
      id: 9,
      car: 'Jeep',
      car_model: 'Grand Cherokee',
      color: 'Goldenrod',
      car_vin: 'WDDEJ7GB7CA797189',
      location: 'France',
    },
    {
      id: 10,
      car: 'Cadillac',
      car_model: 'Eldorado',
      color: 'Puce',
      car_vin: 'WAUEG94FX6N634946',
      location: 'Poland',
    },
    {
      id: 11,
      car: 'Ford',
      car_model: 'Econoline E350',
      color: 'Green',
      car_vin: 'WBAKG7C55DJ142846',
      location: 'Poland',
    },
    {
      id: 12,
      car: 'Toyota',
      car_model: '4Runner',
      color: 'Puce',
      car_vin: '1FTMF1E89AK908258',
      location: 'Russia',
    },
    {
      id: 13,
      car: 'Jeep',
      car_model: 'Cherokee',
      color: 'Mauv',
      car_vin: 'WBAYM1C5XFD969159',
      location: 'Poland',
    },
    {
      id: 14,
      car: 'Hyundai',
      car_model: 'Tiburon',
      color: 'Violet',
      car_vin: 'WP0CB2A81FS776478',
      location: 'Belarus',
    },
    {
      id: 15,
      car: 'Chevrolet',
      car_model: 'Silverado 1500',
      color: 'Fuscia',
      car_vin: '5J6YH1H31BL684200',
      location: 'Russia',
    },
    {
      id: 16,
      car: 'Dodge',
      car_model: 'Aspen',
      color: 'Aquamarine',
      car_vin: '1N6BF0KX6FN496464',
      location: 'France',
    },
    {
      id: 17,
      car: 'BMW',
      car_model: 'M3',
      color: 'Purple',
      car_vin: 'WBAKA4C50CC120241',
      location: 'Russia',
    },
    {
      id: 18,
      car: 'Oldsmobile',
      car_model: 'Silhouette',
      color: 'Blue',
      car_vin: 'SCBZB25E22C076440',
      location: 'France',
    },
    {
      id: 19,
      car: 'Ford',
      car_model: 'Bronco',
      color: 'Purple',
      car_vin: 'WAUEFAFL8DA739061',
      location: 'Poland',
    },
    {
      id: 20,
      car: 'Kia',
      car_model: 'Sedona',
      color: 'Pink',
      car_vin: '1D4RE2GG8BC957245',
      location: 'Russia',
    },
    {
      id: 21,
      car: 'Infiniti',
      car_model: 'Q',
      color: 'Crimson',
      car_vin: '3GTU2YEJ4CG719084',
      location: 'Russia',
    },
    {
      id: 22,
      car: 'GMC',
      car_model: 'Yukon Denali',
      color: 'Maroon',
      car_vin: '2T1BURHEXFC838925',
      location: 'Poland',
    },
    {
      id: 23,
      car: 'Porsche',
      car_model: 'Boxster',
      color: 'Goldenrod',
      car_vin: '3VW217AU7FM726800',
      location: 'Russia',
    },
    {
      id: 24,
      car: 'GMC',
      car_model: 'Jimmy',
      color: 'Red',
      car_vin: '1G6DC5EG5A0832806',
      location: 'France',
    },
    {
      id: 25,
      car: 'Toyota',
      car_model: 'Tacoma Xtra',
      color: 'Blue',
      car_vin: '1C4PJLAB3FW030841',
      location: 'Russia',
    },
    {
      id: 26,
      car: 'Honda',
      car_model: 'Civic',
      color: 'Khaki',
      car_vin: 'WAUVT58E53A613138',
      location: 'Russia',
    },
    {
      id: 27,
      car: 'Buick',
      car_model: 'Lucerne',
      color: 'Indigo',
      car_vin: 'YV4902DZ2B2855850',
      location: 'Russia',
    },
    {
      id: 28,
      car: 'Chevrolet',
      car_model: 'Corvette',
      color: 'Red',
      car_vin: 'SALVP1BG2CH257645',
      location: 'Russia',
    },
    {
      id: 29,
      car: 'Chevrolet',
      car_model: 'Venture',
      color: 'Crimson',
      car_vin: '1G4GL5G35DF345316',
      location: 'France',
    },
    {
      id: 30,
      car: 'Lotus',
      car_model: 'Esprit',
      color: 'Fuscia',
      car_vin: 'WAU3GBFCXDN990005',
      location: 'France',
    },
    {
      id: 31,
      car: 'Plymouth',
      car_model: 'Colt',
      color: 'Orange',
      car_vin: '1G6DM5E35D0911942',
      location: 'Poland',
    },
    {
      id: 32,
      car: 'Volkswagen',
      car_model: 'Jetta',
      color: 'Orange',
      car_vin: 'WBAUN1C58AV709759',
      location: 'Poland',
    },
    {
      id: 33,
      car: 'Plymouth',
      car_model: 'Acclaim',
      color: 'Pink',
      car_vin: 'JM1CR2W35A0350287',
      location: 'Poland',
    },
    {
      id: 34,
      car: 'Ford',
      car_model: 'F250',
      color: 'Mauv',
      car_vin: '3N1BC1AP1BL379908',
      location: 'France',
    },
    {
      id: 35,
      car: 'Chevrolet',
      car_model: 'Corvette',
      color: 'Yellow',
      car_vin: 'WBAEW53495P807595',
      location: 'France',
    },
    {
      id: 36,
      car: 'Lincoln',
      car_model: 'Navigator',
      color: 'Maroon',
      car_vin: '4F2CY0C70AK935829',
      location: 'France',
    },
    {
      id: 37,
      car: 'Chevrolet',
      car_model: 'Express 2500',
      color: 'Maroon',
      car_vin: '19VDE3F79EE647996',
      location: 'Russia',
    },
    {
      id: 38,
      car: 'Chevrolet',
      car_model: 'Express 2500',
      color: 'Yellow',
      car_vin: '1G4HR57Y57U707059',
      location: 'Georgia',
    },
    {
      id: 39,
      car: 'GMC',
      car_model: '3500',
      color: 'Violet',
      car_vin: 'WA1EY74L48D815943',
      location: 'Poland',
    },
    {
      id: 40,
      car: 'Nissan',
      car_model: '350Z Roadster',
      color: 'Aquamarine',
      car_vin: 'TRURD38J791030426',
      location: 'Russia',
    },
    {
      id: 41,
      car: 'GMC',
      car_model: 'Savana 3500',
      color: 'Yellow',
      car_vin: 'WVWDB7AJ0EW759988',
      location: 'Russia',
    },
    {
      id: 42,
      car: 'Ford',
      car_model: 'Explorer Sport Trac',
      color: 'Red',
      car_vin: 'KMHEC4A46FA406689',
      location: 'Poland',
    },
    {
      id: 43,
      car: 'Chrysler',
      car_model: 'Fifth Ave',
      color: 'Aquamarine',
      car_vin: 'SCBGH3ZA5EC809149',
      location: 'Poland',
    },
    {
      id: 44,
      car: 'Toyota',
      car_model: 'Corolla',
      color: 'Turquoise',
      car_vin: 'JH4CW2H57DC759013',
      location: 'Russia',
    },
    {
      id: 45,
      car: 'MINI',
      car_model: 'Cooper',
      color: 'Orange',
      car_vin: 'WVGAV7AX0AW188717',
      location: 'Poland',
    },
    {
      id: 46,
      car: 'Ford',
      car_model: 'F150',
      color: 'Blue',
      car_vin: '2T1BURHE6EC886789',
      location: 'Russia',
    },
    {
      id: 47,
      car: 'Ford',
      car_model: 'E-350 Super Duty',
      color: 'Purple',
      car_vin: 'JN1AJ0HP4BM095261',
      location: 'France',
    },
    {
      id: 48,
      car: 'Volvo',
      car_model: '940',
      color: 'Purple',
      car_vin: 'WAURGAFD4EN969536',
      location: 'Russia',
    },
    {
      id: 49,
      car: 'BMW',
      car_model: '650',
      color: 'Puce',
      car_vin: 'KNAFT4A29A5773754',
      location: 'Russia',
    },
    {
      id: 50,
      car: 'Lamborghini',
      car_model: 'Countach',
      color: 'Maroon',
      car_vin: 'WBA3D3C50EK857292',
      location: 'Russia',
    },
  ],
};

export default STATE;
